### ISSUE TITLE
Difference with flutter_secure_storage ?

### ISSUE THREAD

**Issue by pierremrtn** [koji-1009/flutter_secure_storage#48]
This package seems to be a copy of flutter_secure_storage.
What are the differences with flutter_secure_storage ?

**Comment by koji-1009** [comment]
https://github.com/juliansteenbakker/flutter_secure_storage/compare/develop...koji-1009:flutter_secure_storage:main

**Comment by pierremrtn** [comment]
It would be nice to add a section at the top of the readme to explain that this is a fork and the reasons behind it, as others packages usually do.
Right now this is quite confusing.
